<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Rpcsvc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message containing the greetings
 *
 * Generated from protobuf message <code>rpcsvc.CheckResp</code>
 */
class CheckResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     */
    protected $Code = '';
    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     */
    protected $Msg = '';
    /**
     * Generated from protobuf field <code>string ReturnStr = 3;</code>
     */
    protected $ReturnStr = '';
    /**
     * Generated from protobuf field <code>repeated .rpcsvc.WordData WordList = 4;</code>
     */
    private $WordList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Code
     *     @type string $Msg
     *     @type string $ReturnStr
     *     @type array<\Rpcsvc\WordData>|\Google\Protobuf\Internal\RepeatedField $WordList
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->Msg;
    }

    /**
     * Generated from protobuf field <code>string Msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->Msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReturnStr = 3;</code>
     * @return string
     */
    public function getReturnStr()
    {
        return $this->ReturnStr;
    }

    /**
     * Generated from protobuf field <code>string ReturnStr = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReturnStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReturnStr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rpcsvc.WordData WordList = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWordList()
    {
        return $this->WordList;
    }

    /**
     * Generated from protobuf field <code>repeated .rpcsvc.WordData WordList = 4;</code>
     * @param array<\Rpcsvc\WordData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWordList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rpcsvc\WordData::class);
        $this->WordList = $arr;

        return $this;
    }

}

