<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Rpcsvc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpcsvc.WordData</code>
 */
class WordData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Keyword = 1;</code>
     */
    protected $Keyword = '';
    /**
     * Generated from protobuf field <code>string Category = 2;</code>
     */
    protected $Category = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Keyword
     *     @type string $Category
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Keyword = 1;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->Keyword;
    }

    /**
     * Generated from protobuf field <code>string Keyword = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Keyword = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Category = 2;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->Category;
    }

    /**
     * Generated from protobuf field <code>string Category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->Category = $var;

        return $this;
    }

}

